### ISSUE TITLE
Two Questions

### ISSUE THREAD

**Issue by delldu** [wangyins/transformer-for-image-colorization#2]
Dear friend,
    Thanks for your good job !
    Now we have two questions, hope to get your help:
    1) What's the meaning for "ab_constant_filter.npy", "weight_index.npy" ?  How to create them from source ?
    2) Where can we got the beautiful target and reference images of paper ? Would your like to share us ?
Best Regards,

**Comment by wangyins** [comment]
> Dear friend, Thanks for your good job ! Now we have two questions, hope to get your help: 1) What's the meaning for "ab_constant_filter.npy", "weight_index.npy" ? How to create them from source ? 2) Where can we got the beautiful target and reference images of paper ? Would your like to share us ? Best Regards,

Dear delldu, I am so sorry to answer your question so late! For your first question, we quantize the ab color space to a 21*21 grid, and the unusual ab value is removed. Thus, 198 ab values have remained, and we denote "ab_constant_filter.npy"  in the code. "weight_index.npy" is the index of 198 ab values in the 21*21 grid. To your second question, we are thinking about when these images are open.

**Comment by wangyins** [comment]
> Dear friend, Thanks for your good job ! Now we have two questions, hope to get your help: 1) What's the meaning for "ab_constant_filter.npy", "weight_index.npy" ? How to create them from source ? 2) Where can we got the beautiful target and reference images of paper ? Would your like to share us ? Best Regards,

Dear delldu, I am so sorry to answer your question so late! For your first question, we quantize the ab color space to a 21*21 grid, and the unusual ab value is removed. Thus, 198 ab values have remained, which is denoted "ab_constant_filter.npy"  in the code. "weight_index.npy" is the index of 198 ab values in the 21*21 grid. To your second question, we are thinking about when these images are open.
